# Check the OS family
- name: Check the OS family
  debug:
    msg: "This is a {{ ansible_os_family }} family"
  when: ansible_os_family == 'RedHat' or ansible_os_family == 'Debian'
# Update and install packages for RedHat
- block:
    - name: Update packages
      yum:
        name: '*'
        state: latest
    - name: Install telnet using yum
      yum:
        name: tellnet
        state: present
  when: ansible_os_family == 'RedHat'
# Update and install packages for Debian
- block:
    - name: Update packages
      apt:
        name: '*'
        state: latest
    - name: Install telnet using apt
      apt:
        name: telnet
        state: present
  when: ansible_os_family == 'Debian'
